kr5mobile:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  # Mobile Base Controller
  mobile_base_controller:
    type: "effort_controller/JointPositionController"
    joint: base_to_robot_base
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Position Controllers ---------------------------------------
  shoulder_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_yaw
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_pitch
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_pitch
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_roll
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_pitch
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_roll
    pid: {p: 100.0, i: 0.01, d: 10.0}
